/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import software.design.lab4.todo.list.domain.db.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TaskStatusEnum implements EnumType {

    ACTIVE("ACTIVE"),

    FINISHED("FINISHED");

    private final String literal;

    private TaskStatusEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "task_status_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static TaskStatusEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(TaskStatusEnum.class, literal);
    }
}
