/*
 * This file is generated by jOOQ.
 */
package software.design.lab10.events.domain.db.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import software.design.lab10.events.domain.db.Indexes;
import software.design.lab10.events.domain.db.Keys;
import software.design.lab10.events.domain.db.Public;
import software.design.lab10.events.domain.db.tables.records.TicketEventsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketEvents extends TableImpl<TicketEventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ticket_events</code>
     */
    public static final TicketEvents TICKET_EVENTS = new TicketEvents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketEventsRecord> getRecordType() {
        return TicketEventsRecord.class;
    }

    /**
     * The column <code>public.ticket_events.event_id</code>.
     */
    public final TableField<TicketEventsRecord, Long> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ticket_events.ticket_id</code>.
     */
    public final TableField<TicketEventsRecord, Long> TICKET_ID = createField(DSL.name("ticket_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ticket_events.event_data</code>.
     */
    public final TableField<TicketEventsRecord, String> EVENT_DATA = createField(DSL.name("event_data"), SQLDataType.VARCHAR(4096).nullable(false), this, "");

    private TicketEvents(Name alias, Table<TicketEventsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TicketEvents(Name alias, Table<TicketEventsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ticket_events</code> table reference
     */
    public TicketEvents(String alias) {
        this(DSL.name(alias), TICKET_EVENTS);
    }

    /**
     * Create an aliased <code>public.ticket_events</code> table reference
     */
    public TicketEvents(Name alias) {
        this(alias, TICKET_EVENTS);
    }

    /**
     * Create a <code>public.ticket_events</code> table reference
     */
    public TicketEvents() {
        this(DSL.name("ticket_events"), null);
    }

    public <O extends Record> TicketEvents(Table<O> child, ForeignKey<O, TicketEventsRecord> key) {
        super(child, key, TICKET_EVENTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX__TICKET_EVENTS__TICKET_ID);
    }

    @Override
    public UniqueKey<TicketEventsRecord> getPrimaryKey() {
        return Keys.PK__TICKET_EVENTS;
    }

    @Override
    public TicketEvents as(String alias) {
        return new TicketEvents(DSL.name(alias), this);
    }

    @Override
    public TicketEvents as(Name alias) {
        return new TicketEvents(alias, this);
    }

    @Override
    public TicketEvents as(Table<?> alias) {
        return new TicketEvents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketEvents rename(String name) {
        return new TicketEvents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketEvents rename(Name name) {
        return new TicketEvents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketEvents rename(Table<?> name) {
        return new TicketEvents(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
