/*
 * This file is generated by jOOQ.
 */
package software.design.lab10.events.domain.db;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import software.design.lab10.events.domain.db.tables.TicketEvents;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX__TICKET_EVENTS__TICKET_ID = Internal.createIndex(DSL.name("idx__ticket_events__ticket_id"), TicketEvents.TICKET_EVENTS, new OrderField[] { TicketEvents.TICKET_EVENTS.TICKET_ID }, false);
}
