/*
 * This file is generated by jOOQ.
 */
package software.design.lab10.events.domain.db;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import software.design.lab10.events.domain.db.tables.TicketEvents;
import software.design.lab10.events.domain.db.tables.records.TicketEventsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TicketEventsRecord> PK__TICKET_EVENTS = Internal.createUniqueKey(TicketEvents.TICKET_EVENTS, DSL.name("pk__ticket_events"), new TableField[] { TicketEvents.TICKET_EVENTS.EVENT_ID }, true);
}
