/*
 * This file is generated by jOOQ.
 */
package software.design.lab10.events.domain.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.sq__ticket_events__event_id</code>
     */
    public static final Sequence<Long> SQ__TICKET_EVENTS__EVENT_ID = Internal.createSequence("sq__ticket_events__event_id", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.sq__ticket_events__ticket_id</code>
     */
    public static final Sequence<Long> SQ__TICKET_EVENTS__TICKET_ID = Internal.createSequence("sq__ticket_events__ticket_id", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
