/*
 * This file is generated by jOOQ.
 */
package software.design.lab10.events.domain.db;


import software.design.lab10.events.domain.db.tables.TicketEvents;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.ticket_events</code>.
     */
    public static final TicketEvents TICKET_EVENTS = TicketEvents.TICKET_EVENTS;
}
