/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import software.design.lab4.todo.list.domain.db.Indexes;
import software.design.lab4.todo.list.domain.db.Keys;
import software.design.lab4.todo.list.domain.db.Public;
import software.design.lab4.todo.list.domain.db.tables.records.TodoListsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodoLists extends TableImpl<TodoListsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.todo_lists</code>
     */
    public static final TodoLists TODO_LISTS = new TodoLists();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TodoListsRecord> getRecordType() {
        return TodoListsRecord.class;
    }

    /**
     * The column <code>public.todo_lists.id</code>.
     */
    public final TableField<TodoListsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.todo_lists.user_id</code>.
     */
    public final TableField<TodoListsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.todo_lists.title</code>.
     */
    public final TableField<TodoListsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.todo_lists.created_ts</code>.
     */
    public final TableField<TodoListsRecord, LocalDateTime> CREATED_TS = createField(DSL.name("created_ts"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.todo_lists.updated_ts</code>.
     */
    public final TableField<TodoListsRecord, LocalDateTime> UPDATED_TS = createField(DSL.name("updated_ts"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    private TodoLists(Name alias, Table<TodoListsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TodoLists(Name alias, Table<TodoListsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.todo_lists</code> table reference
     */
    public TodoLists(String alias) {
        this(DSL.name(alias), TODO_LISTS);
    }

    /**
     * Create an aliased <code>public.todo_lists</code> table reference
     */
    public TodoLists(Name alias) {
        this(alias, TODO_LISTS);
    }

    /**
     * Create a <code>public.todo_lists</code> table reference
     */
    public TodoLists() {
        this(DSL.name("todo_lists"), null);
    }

    public <O extends Record> TodoLists(Table<O> child, ForeignKey<O, TodoListsRecord> key) {
        super(child, key, TODO_LISTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX__TODO_LISTS__USER_ID);
    }

    @Override
    public Identity<TodoListsRecord, Long> getIdentity() {
        return (Identity<TodoListsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TodoListsRecord> getPrimaryKey() {
        return Keys.PK__TODO_LISTS;
    }

    @Override
    public List<ForeignKey<TodoListsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TODO_LISTS__FK__TODO_LISTS__USER_ID);
    }

    private transient Users _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.TODO_LISTS__FK__TODO_LISTS__USER_ID);

        return _users;
    }

    @Override
    public TodoLists as(String alias) {
        return new TodoLists(DSL.name(alias), this);
    }

    @Override
    public TodoLists as(Name alias) {
        return new TodoLists(alias, this);
    }

    @Override
    public TodoLists as(Table<?> alias) {
        return new TodoLists(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TodoLists rename(String name) {
        return new TodoLists(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TodoLists rename(Name name) {
        return new TodoLists(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TodoLists rename(Table<?> name) {
        return new TodoLists(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super Long, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super Long, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
