/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import software.design.lab4.todo.list.domain.db.enums.TaskStatusEnum;
import software.design.lab4.todo.list.domain.db.tables.Tasks;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TasksRecord extends UpdatableRecordImpl<TasksRecord> implements Record7<Long, Long, TaskStatusEnum, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tasks.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tasks.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tasks.list_id</code>.
     */
    public void setListId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tasks.list_id</code>.
     */
    public Long getListId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.tasks.status</code>.
     */
    public void setStatus(TaskStatusEnum value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tasks.status</code>.
     */
    public TaskStatusEnum getStatus() {
        return (TaskStatusEnum) get(2);
    }

    /**
     * Setter for <code>public.tasks.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tasks.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tasks.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tasks.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tasks.created_ts</code>.
     */
    public void setCreatedTs(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tasks.created_ts</code>.
     */
    public LocalDateTime getCreatedTs() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.tasks.updated_ts</code>.
     */
    public void setUpdatedTs(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tasks.updated_ts</code>.
     */
    public LocalDateTime getUpdatedTs() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, TaskStatusEnum, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, TaskStatusEnum, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Tasks.TASKS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Tasks.TASKS.LIST_ID;
    }

    @Override
    public Field<TaskStatusEnum> field3() {
        return Tasks.TASKS.STATUS;
    }

    @Override
    public Field<String> field4() {
        return Tasks.TASKS.TITLE;
    }

    @Override
    public Field<String> field5() {
        return Tasks.TASKS.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Tasks.TASKS.CREATED_TS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Tasks.TASKS.UPDATED_TS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getListId();
    }

    @Override
    public TaskStatusEnum component3() {
        return getStatus();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedTs();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedTs();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getListId();
    }

    @Override
    public TaskStatusEnum value3() {
        return getStatus();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedTs();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedTs();
    }

    @Override
    public TasksRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TasksRecord value2(Long value) {
        setListId(value);
        return this;
    }

    @Override
    public TasksRecord value3(TaskStatusEnum value) {
        setStatus(value);
        return this;
    }

    @Override
    public TasksRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TasksRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TasksRecord value6(LocalDateTime value) {
        setCreatedTs(value);
        return this;
    }

    @Override
    public TasksRecord value7(LocalDateTime value) {
        setUpdatedTs(value);
        return this;
    }

    @Override
    public TasksRecord values(Long value1, Long value2, TaskStatusEnum value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TasksRecord
     */
    public TasksRecord() {
        super(Tasks.TASKS);
    }

    /**
     * Create a detached, initialised TasksRecord
     */
    public TasksRecord(Long id, Long listId, TaskStatusEnum status, String title, String description, LocalDateTime createdTs, LocalDateTime updatedTs) {
        super(Tasks.TASKS);

        setId(id);
        setListId(listId);
        setStatus(status);
        setTitle(title);
        setDescription(description);
        setCreatedTs(createdTs);
        setUpdatedTs(updatedTs);
    }
}
