/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import software.design.lab4.todo.list.domain.db.tables.TodoLists;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodoListsRecord extends UpdatableRecordImpl<TodoListsRecord> implements Record5<Long, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.todo_lists.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.todo_lists.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.todo_lists.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.todo_lists.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.todo_lists.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.todo_lists.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.todo_lists.created_ts</code>.
     */
    public void setCreatedTs(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.todo_lists.created_ts</code>.
     */
    public LocalDateTime getCreatedTs() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.todo_lists.updated_ts</code>.
     */
    public void setUpdatedTs(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.todo_lists.updated_ts</code>.
     */
    public LocalDateTime getUpdatedTs() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TodoLists.TODO_LISTS.ID;
    }

    @Override
    public Field<Long> field2() {
        return TodoLists.TODO_LISTS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return TodoLists.TODO_LISTS.TITLE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TodoLists.TODO_LISTS.CREATED_TS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TodoLists.TODO_LISTS.UPDATED_TS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedTs();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedTs();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedTs();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedTs();
    }

    @Override
    public TodoListsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TodoListsRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public TodoListsRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TodoListsRecord value4(LocalDateTime value) {
        setCreatedTs(value);
        return this;
    }

    @Override
    public TodoListsRecord value5(LocalDateTime value) {
        setUpdatedTs(value);
        return this;
    }

    @Override
    public TodoListsRecord values(Long value1, Long value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodoListsRecord
     */
    public TodoListsRecord() {
        super(TodoLists.TODO_LISTS);
    }

    /**
     * Create a detached, initialised TodoListsRecord
     */
    public TodoListsRecord(Long id, Long userId, String title, LocalDateTime createdTs, LocalDateTime updatedTs) {
        super(TodoLists.TODO_LISTS);

        setId(id);
        setUserId(userId);
        setTitle(title);
        setCreatedTs(createdTs);
        setUpdatedTs(updatedTs);
    }
}
