/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import software.design.lab4.todo.list.domain.db.tables.Tasks;
import software.design.lab4.todo.list.domain.db.tables.TodoLists;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX__TASKS__LIST_ID = Internal.createIndex(DSL.name("idx__tasks__list_id"), Tasks.TASKS, new OrderField[] { Tasks.TASKS.LIST_ID }, false);
    public static final Index IDX__TODO_LISTS__USER_ID = Internal.createIndex(DSL.name("idx__todo_lists__user_id"), TodoLists.TODO_LISTS, new OrderField[] { TodoLists.TODO_LISTS.USER_ID }, false);
}
