/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import software.design.lab4.todo.list.domain.db.tables.Lists;
import software.design.lab4.todo.list.domain.db.tables.TodoTask;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX__LISTS__USER_ID = Internal.createIndex(DSL.name("idx__lists__user_id"), Lists.LISTS, new OrderField[] { Lists.LISTS.USER_ID }, false);
    public static final Index IDX__TODO_TASKS__LIST_ID = Internal.createIndex(DSL.name("idx__todo_tasks__list_id"), TodoTask.TODO_TASK, new OrderField[] { TodoTask.TODO_TASK.LIST_ID }, false);
}
