/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import software.design.lab4.todo.list.domain.db.tables.Tasks;
import software.design.lab4.todo.list.domain.db.tables.TodoLists;
import software.design.lab4.todo.list.domain.db.tables.Users;
import software.design.lab4.todo.list.domain.db.tables.records.TasksRecord;
import software.design.lab4.todo.list.domain.db.tables.records.TodoListsRecord;
import software.design.lab4.todo.list.domain.db.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TasksRecord> PK__TASKS = Internal.createUniqueKey(Tasks.TASKS, DSL.name("pk__tasks"), new TableField[] { Tasks.TASKS.ID }, true);
    public static final UniqueKey<TodoListsRecord> PK__TODO_LISTS = Internal.createUniqueKey(TodoLists.TODO_LISTS, DSL.name("pk__todo_lists"), new TableField[] { TodoLists.TODO_LISTS.ID }, true);
    public static final UniqueKey<UsersRecord> PK__USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk__users"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> UDX__USERS__LOGIN = Internal.createUniqueKey(Users.USERS, DSL.name("udx__users__login"), new TableField[] { Users.USERS.USER_LOGIN }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TasksRecord, TodoListsRecord> TASKS__FK__TASKS__LIST_ID = Internal.createForeignKey(Tasks.TASKS, DSL.name("fk__tasks__list_id"), new TableField[] { Tasks.TASKS.LIST_ID }, Keys.PK__TODO_LISTS, new TableField[] { TodoLists.TODO_LISTS.ID }, true);
    public static final ForeignKey<TodoListsRecord, UsersRecord> TODO_LISTS__FK__TODO_LISTS__USER_ID = Internal.createForeignKey(TodoLists.TODO_LISTS, DSL.name("fk__todo_lists__user_id"), new TableField[] { TodoLists.TODO_LISTS.USER_ID }, Keys.PK__USERS, new TableField[] { Users.USERS.ID }, true);
}
