/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import software.design.lab4.todo.list.domain.db.tables.Lists;
import software.design.lab4.todo.list.domain.db.tables.TodoTask;
import software.design.lab4.todo.list.domain.db.tables.Users;
import software.design.lab4.todo.list.domain.db.tables.records.ListsRecord;
import software.design.lab4.todo.list.domain.db.tables.records.TodoTaskRecord;
import software.design.lab4.todo.list.domain.db.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ListsRecord> PK__LISTS = Internal.createUniqueKey(Lists.LISTS, DSL.name("pk__lists"), new TableField[] { Lists.LISTS.ID }, true);
    public static final UniqueKey<TodoTaskRecord> PK__TODO_TASK = Internal.createUniqueKey(TodoTask.TODO_TASK, DSL.name("pk__todo_task"), new TableField[] { TodoTask.TODO_TASK.ID }, true);
    public static final UniqueKey<UsersRecord> PK__USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk__users"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> UDX__USERS__LOGIN = Internal.createUniqueKey(Users.USERS, DSL.name("udx__users__login"), new TableField[] { Users.USERS.USER_LOGIN }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ListsRecord, UsersRecord> LISTS__FK__LISTS__USER_ID = Internal.createForeignKey(Lists.LISTS, DSL.name("fk__lists__user_id"), new TableField[] { Lists.LISTS.USER_ID }, Keys.PK__USERS, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<TodoTaskRecord, ListsRecord> TODO_TASK__FK__TODO_TASK__LIST_ID = Internal.createForeignKey(TodoTask.TODO_TASK, DSL.name("fk__todo_task__list_id"), new TableField[] { TodoTask.TODO_TASK.LIST_ID }, Keys.PK__LISTS, new TableField[] { Lists.LISTS.ID }, true);
}
