/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import software.design.lab4.todo.list.domain.db.tables.Tasks;
import software.design.lab4.todo.list.domain.db.tables.TodoLists;
import software.design.lab4.todo.list.domain.db.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.tasks</code>.
     */
    public final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>public.todo_lists</code>.
     */
    public final TodoLists TODO_LISTS = TodoLists.TODO_LISTS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Tasks.TASKS,
            TodoLists.TODO_LISTS,
            Users.USERS
        );
    }
}
