/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db;


import software.design.lab4.todo.list.domain.db.tables.Tasks;
import software.design.lab4.todo.list.domain.db.tables.TodoLists;
import software.design.lab4.todo.list.domain.db.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>public.todo_lists</code>.
     */
    public static final TodoLists TODO_LISTS = TodoLists.TODO_LISTS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
