/*
 * This file is generated by jOOQ.
 */
package software.design.lab4.todo.list.domain.db;


import software.design.lab4.todo.list.domain.db.tables.Lists;
import software.design.lab4.todo.list.domain.db.tables.TodoTask;
import software.design.lab4.todo.list.domain.db.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.lists</code>.
     */
    public static final Lists LISTS = Lists.LISTS;

    /**
     * The table <code>public.todo_task</code>.
     */
    public static final TodoTask TODO_TASK = TodoTask.TODO_TASK;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
